### ISSUE TITLE
changelog script throws error: "Could not find base or head reference."

### ISSUE THREAD

**Issue by jospoortvliet** [nextcloud/github_helper#16]
Running this:
```$ php index.php generate:changelog server v15.0.5 v15.0.6  --format=html```
I get:
```
repo: server
base: v15.0.5
head: v15.0.6
Checking milestone 15.0.6 for pending PRs ...
 Fetching PR titles for survey_client ...
 45/54 [=======================>----]  83%
 Remaining: 6 secsCould not find base or head reference.
```

**Comment by jospoortvliet** [comment]
I tried to disable repo's but that didn't help :cry:

**Comment by MorrisJobke** [comment]
You need to fetch the latest version, but I also created a PR already ;)

**Comment by jospoortvliet** [comment]
Hmmm I did a 'git fetch' but still same error :cry:

**Comment by MorrisJobke** [comment]
> Hmmm I did a 'git fetch' but still same error 😢

You need to do a git pull, because otherwise the old git branch is checked out and the new data is only fetched but not checked out as local files.

**Comment by jospoortvliet** [comment]
Well I did a 
```
git pull --rebase
Already up to date.
Current branch master is up to date.
```
many times, including just now... somehow that didn't work either? I dunno, I'm on master, always am/was. Is that wrong, as you mention 'old git branch'?

**Comment by MorrisJobke** [comment]
This is the commit that fixed it 4 weeks ago: 764bc8e

**Comment by MorrisJobke** [comment]
Ah - you use two tags and not branches - let me check that out.

**Comment by MorrisJobke** [comment]
Right - I only fixed it for stable14 and stable15 but not for arbitrary tags. Let me try this then as well.
