### ISSUE TITLE
changelog script: do not use compare

### ISSUE THREAD

**Issue by rullzer** [nextcloud/github_helper#17]
https://developer.github.com/v3/repos/commits/#compare-two-commits

This returns max 250 commits. Which is not enough.

**Comment by MorrisJobke** [comment]
@rullzer Do you have two example commits?

**Comment by jospoortvliet** [comment]
Try Nextcloud 15 and 16 - if you can get us a full changelog for https://nextcloud.com/changelog/ then that would be awesome :smile_cat:

**Comment by MorrisJobke** [comment]
> Try Nextcloud 15 and 16 - if you can get us a full changelog for https://nextcloud.com/changelog/ then that would be awesome 😸

THat's not really gonna happen. Because this would be a total mess of what is ported where. We had some stuff being ported over between branches. Also it doesn't really make sense to have a that long list. It is basically 600 to 800 links ... IMO nothing that is properly more readable nor more valuable than to go directly to GitHub and search there.

**Comment by jospoortvliet** [comment]
Allright, so if you're sure this is only a problem for cases where there are more than 250 commits, aka major releases, I'm good - there will the never be a full changelog for those, but that's fine with me. I will update our changelog with that notion.

Note that I had the impression from talking to Roeland that this can also be an issue for minor releases, but I might have mis-understood that. Re-open if that is the case...

**Comment by MorrisJobke** [comment]
> Note that I had the impression from talking to Roeland that this can also be an issue for minor releases, but I might have mis-understood that. Re-open if that is the case...

we rarely have minor releases with 250 commits ... I could be wrong, but I doubt that.

The problem: I would need to change the script heavily and currently I don't have time to do so.
