### ISSUE TITLE
changelog broken for 15.0.14? "Could not find base or head reference."

### ISSUE THREAD

**Issue by jospoortvliet** [nextcloud/github_helper#20]
> $ php index.php generate:changelog server v15.0.13 stable15  --format=html
> repo: server
> base: v15.0.13
> head: stable15
> Checking milestone 15.0.14 for pending PRs ...
> Fetching PR titles for activity ...
>  9/45 [=====>----------------------]  20%
> Remaining: 20 secsCould not find base or head reference.

Ref - https://github.com/nextcloud/github_helper/issues/16 - no clue if that is related. @rullzer I know you're busy but this blocks me for updating the site :(

EDIT: same for 16.0.6 and 17.0.1
Does work for 15.0.12 and 17.0.0! So something is broken wrt the latest releases.

**Comment by rullzer** [comment]
https://gist.github.com/rullzer/1548492f57b981279b893eb2a45ce02e

https://gist.github.com/rullzer/c5b66c2ea7b860d48bed6836e77a1597

https://gist.github.com/rullzer/9bc85965924207d5ac8e21bc5c936438

**Comment by jospoortvliet** [comment]
Thanks!

**Comment by rullzer** [comment]
Nah it is because we archived some repos

**Comment by jospoortvliet** [comment]
Arthur created a fix-ish thing that at least warns what the issue is, let me close this.

**Comment by blizzz** [comment]
for the record, it is https://github.com/nextcloud/github_helper/pull/21
